GaripSozluk.WebApp/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GaripSozluk.Business.Interfaces;
using GaripSozluk.Common.Enums;
using GaripSozluk.Common.Extensions;
using GaripSozluk.Common.ViewModels.Api;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace GaripSozluk.WebApp.Controllers
{
    public class ApiController : Controller
    {
        private readonly ILogger<ApiController> _logger;

        private readonly IHeaderService _headerService;

        private readonly IOpenLibraryApiService _openLibraryApiService;

        public ApiController(ILogger<ApiController> logger,
            IHeaderService headerService,
            IOpenLibraryApiService openLibraryApiService)
        {
            _logger = logger;
            _headerService = headerService;
            _openLibraryApiService = openLibraryApiService;
        }

        public IActionResult ApiSearch()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ApiSearch(ApiSearchVM model)
        {
            if (ModelState.IsValid)
            {
                return Redirect(this.Action<ApiController>(nameof(ApiResult), new { queryText = model.QueryText, searchType = model.SearchType }));
            }

            return View(model);
        }

        public IActionResult ApiResult(string queryText, ApiSearchTypeEnum searchType)
        {
            if (queryText.Length == 0)
            {
                return Redirect(this.Action<ApiController>(nameof(ApiSearch)));
            }

            // API
            var result = _openLibraryApiService.Search(queryText, searchType);
            if (result.ResultModel.Docs.Count > 0)
            {
                return View(result);
            }
            else
            {
                return Redirect(this.Action<ApiController>(nameof(ApiSearch)));
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult InsertTitles(List<string> titles)
        {
            var statusText = "{0} adet başlıktan {1} adet başlığın eklenmesi başarıyla tamamlandı.";

            try
            {
                var insertedTitleCount = _headerService.BulkInsert(HttpContext.User, titles);

                if (insertedTitleCount > 0)
                {
                    if (titles.Count == insertedTitleCount)
                    {
                        statusText = "Tüm başlıklar başarıyla eklendi.";
                    }
                    else
                    {
                        statusText = string.Format(statusText, titles.Count, insertedTitleCount);
                    }
                }
                else
                {
                    statusText = "Seçilen başlıklar daha önce eklenmiş.";
                }

                return Content(JsonConvert.SerializeObject(new
                {
                    status = "success",
                    message = statusText,
                    returnUrl = this.Action<HomeController>(nameof(Index))
                }));
            }
            catch (Exception ex)
            {
                return Content(JsonConvert.SerializeObject(new { status = "error", message = ex.Message }));
            }
        }
    }
}

GaripSozluk.WebApp/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GaripSozluk.Business.Interfaces;
using GaripSozluk.Common.ViewModels.Log;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace GaripSozluk.WebApp.Controllers
{
    public class LogController : Controller
    {
        private readonly ILogger<LogController> _logger;
        private readonly ILogService _logService;

        public LogController(ILogger<LogController> logger,
            ILogService logService)
        {
            _logger = logger;
            _logService = logService;
        }

        public IActionResult LogList()
        {
            var model = new LogResultVM();
            model.Logs = _logService.GetAll();

            return View(model);
        }

        [HttpPost]
        public IActionResult LogList(LogResultVM model)
        {
            model.Logs = _logService.GetAll();

            if (model.FirstDate.HasValue || model.LastDate.HasValue)
            {
                //Do filter
                model.FilteredLogs = _logService.GetAllByDateFilter(model.FirstDate, model.LastDate);
            }

            return View(model);
        }
    }
}

GaripSozluk.WebApp/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GaripSozluk.Business.Interfaces;
using GaripSozluk.Common.Extensions;
using GaripSozluk.Common.ViewModels.Header;
using GaripSozluk.Common.ViewModels.Post;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace GaripSozluk.WebApp.Controllers
{

    //ToDo: OK! Tüm actionların üzerine authorize attribute eklemek yerine bir kere controller seviyesine ekleyebilirsin. 
    [Authorize]
    public class PostController : Controller
    {
        private readonly ILogger<PostController> _logger;
        private readonly ICategoryService _categoryService;
        private readonly IHeaderService _headerService;
        private readonly IPostService _postService;
        private readonly IUserService _userService;

        public PostController(ILogger<PostController> logger,
            ICategoryService categoryService,
            IHeaderService headerService,
            IPostService postService,
            IUserService userService)
        {
            _logger = logger;

            _categoryService = categoryService;
            _headerService = headerService;
            _postService = postService;

            _userService = userService;
        }

        public IActionResult AddHeader(string categoryCode)
        {
            ViewBag.CategorySelectItemList = _categoryService.GetCategoriesOptionList();

            var model = new NewHeaderVM();
            model.CategoryCode = categoryCode;

            return View(model);
        }

        [HttpPost]
        public IActionResult AddHeader(NewHeaderVM model)
        {
            if (ModelState.IsValid)
            {
                if (_headerService.AddNewHeader(HttpContext.User, model))
                {
                    return Redirect(this.Action<HomeController>(nameof(Index), new { categoryCode = model.CategoryCode, headerCode = model.HeaderCode }));
                }
            }

            ViewBag.CategorySelectItemList = _categoryService.GetCategoriesOptionList();

            return View(model);
        }

        public IActionResult AddPost(string CategoryCode, string headerCode)
        {
            var model = new NewPostVM();
            model.HeaderCode = headerCode;
            model.CategoryCode = CategoryCode;

            return View(model);
        }

        [HttpPost]
        public IActionResult AddPost(NewPostVM model)
        {
            if (ModelState.IsValid)
            {
                if (_headerService.AddNewPost(HttpContext.User, model))
                {
                    return Redirect(this.Action<HomeController>(nameof(Index), new { categoryCode = model.CategoryCode, headerCode = model.HeaderCode }));
                }
            }

            return View(model);
        }

        public IActionResult UpVote(string categoryCode, string headerCode, int postId, int pageNumber)
        {
            _postService.UpVote(HttpContext.User, postId);
            return Redirect(this.Action<HomeController>(nameof(Index), new { categoryCode = categoryCode, headerCode = headerCode, pageNumber = pageNumber }));
        }

        public IActionResult DownVote(string categoryCode, string headerCode, int postId, int pageNumber)
        {
            _postService.DownVote(HttpContext.User, postId);
            return Redirect(this.Action<HomeController>(nameof(Index), new { categoryCode = categoryCode, headerCode = headerCode, pageNumber = pageNumber }));
        }
    }
}

GaripSozluk.WebApp/Views/Shared/_Layout.cshtml
@inject ICategoryService CategoryService
@inject IHeaderService HeaderService
@{

    var pathParts = Context.Request.Path.ToString().Split("/").ToList();
    pathParts = pathParts.Where(x => x != string.Empty).ToList();

    string headerCode = "";

    if (pathParts.Count > 3)
    {
        headerCode = pathParts[3];
    }

    string categoryCode = "";

    if (pathParts.Count > 2)
    {
        categoryCode = pathParts[2];
    }
    else
    {
        categoryCode = CategoryService.GetCategoryIdCodeById(0);
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-sweetalert/dist/sweetalert.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="nav-fill">
    <div class="modal fade" id="advancedSearchModal">
        <form class="mr-auto d-sm-none d-md-block" asp-controller="Home" asp-action="Index" method="post">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title display-4 text-success">Detaylı Ara</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="CategoryId" value="@(categoryCode)" />
                        <input type="hidden" name="HeaderId" value="@(headerCode)" />
                        <input type="hidden" name="PageNumber" value="1" />
                        <div class="form-group">
                            <input type="text" class="form-control" data-val="true" name="SearchText" placeholder="Arama yap..." required>
                        </div>
                        <div class="form-group">
                            <label>Aralık Başlangıç Tarihi:</label>
                            <input type="date" class="form-control" name="StartDate" id="searchStartDate" min="2020-01-01" max="@DateTime.Now.Date.ToString("yyyy-MM-dd")">
                        </div>
                        <div class="form-group">
                            <label>Aralık Bitiş Tarihi:</label>
                            <input type="date" class="form-control" name="EndDate" id="searchEndDate" max="@DateTime.Now.Date.ToString("yyyy-MM-dd")">
                        </div>
                        <div class="form-group">
                            <label>Sıralama:</label>
                            <select name="InvertOrder" class="form-control">
                                <option value="False">A'dan Z'ye</option>
                                <option value="True">Z'den A'ya</option>
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-outline-success" type="submit">Detaylı Ara</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <nav class="navbar navbar-expand-sm bg-success navbar-dark sticky-top">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="https://emojis.wiki/emoji-pics/apple/eye-apple.png" width="30" height="30" class="d-inline-block align-top">
            GARİP SÖZLÜK
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Api" asp-action="ApiSearch">Api Arama</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="ApiHeaderList">Api Başlıklar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Log" asp-action="LogList">Log Listesi</a>
                </li>
            </ul>
            <form class="mr-auto d-sm-none d-md-block" asp-controller="Home" asp-action="Index" method="post">
                <div class="input-group">
                    <input type="text" class="form-control" data-val="true" name="SearchText" placeholder="Arama yap...">

                    <input type="hidden" name="CategoryId" value="@(categoryCode)" />
                    <input type="hidden" name="HeaderId" value="@(headerCode)" />
                    <input type="hidden" name="PageNumber" value="1" />

                    <div class="dropdown input-group-append">
                        <button type="button" class="btn btn-outline-light" data-toggle="modal" data-target="#advancedSearchModal">
                            <i class="fa fa-sort-down"></i>
                        </button>
                    </div>
                    <div class="input-group-append">
                        <button class="btn btn-outline-light" type="submit">Ara</button>
                    </div>
                </div>
            </form>
            <ul class="navbar-nav">
                <li>
                    <div class="input-group">
                        <div class="input-group-append mx-auto">
                            <a class="nav-link mr-2" style="width:80px" asp-controller="Home" asp-action="Random" asp-route-categoryCode="@categoryCode">Rastgele</a>
                            @if (Context.User.Identity.IsAuthenticated)
                            {
                                <a class="text-warning nav-link mr-2" asp-controller="Post" asp-action="AddHeader" asp-route-categoryCode="@categoryCode">Yeni Başlık Ekle</a>
                                <a class="nav-link text-white mr-2" asp-controller="Account" asp-action="GetBlockedUsersList">@(Context.User.Identity.Name)</a>
                                <a class="nav-link mr-2" style="width:80px" asp-controller="Account" asp-action="Logout">Çıkış</a> }
                            else
                            {
                                <a class="nav-link mr-2" style="width:80px" asp-controller="Account" asp-action="Login">Giriş Yap</a>
                                <a class="nav-link mr-2" style="width:80px" asp-controller="Account" asp-action="Register">Kaydol</a>}
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <nav class="navbar navbar-expand-sm bg-success navbar-dark shadow rounded-bottom small">
        <div class="container justify-content-center">
            <ul class="nav justify-content-center">
                @foreach (var category in CategoryService.GetCategories())
                {
                    var categoryText = category.Value;

                    if (category.Value == "Kitap")
                    {
                        categoryText = "<i class=\"fa fa-book\"></i> " + categoryText;
                    }

                    <li class="nav-item">
                        @if (headerCode != "")
                        {
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Index" asp-route-categoryCode="@category.Key" asp-route-HeaderCode="@headerCode">@Html.Raw(categoryText)</a>
                        }
                        else
                        {
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Index" asp-route-categoryCode="@category.Key">@Html.Raw(categoryText)</a>
                        }
                    </li>
                }
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="d-flex flex-column-reverse flex-md-row">
            @if (ViewData["NoSidebar"] == null)
            {
                <div class="col-md-4 col-lg-3 border-right overflow-hidden">
                    <p class="text-muted mt-3 ml-8">
                        <a class="btn btn-light bg-white" asp-controller="Home" asp-action="Index" asp-route-categoryCode="@categoryCode">
                            @CategoryService.GetCategoryNameByIdCode(categoryCode)
                        </a>
                    </p>
                    <div class="pl-2">
                        <ul class="list-group">
                            @foreach (var item in HeaderService.GetHeadersByCategoryId(User, categoryCode))
                            {
                                <li class="list-group-item border-0 m-1 p-1">
                                    <a class="btn btn-light btn-block text-left bg-white d-flex justify-content-between align-items-center" asp-controller="Home" asp-action="Index" asp-route-HeaderCode="@item.HeaderCode" asp-route-categoryCode="@categoryCode">
                                        @item.Title
                                        @if (item.PostCount > 0)
                                        {
                                            <span class="badge badge-success badge-pill">@item.PostCount</span>}
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                    <p class="text-muted mt-3 ml-8"></p>
                </div>
                <div class="col-md-8 col-lg-9 h-100 d-inline-block">
                    <div class="container">
                        @RenderBody()
                    </div>
                </div>
            }
            else
            {
                <div class="col-12 h-100 d-inline-block">
                    <div class="container">
                        @RenderBody()
                    </div>
                </div>
            }

        </div>
        <footer class="d-flex flex-row border-top footer text-muted">
            <div class="col-md-3 text-center">
                <a class="text-success" href="#">Link 1</a>
            </div>
            <div class="col-md-3 text-center">
                <a class="text-success" href="#">Link 2</a>
            </div>
            <div class="col-md-3 text-center">
                <a class="text-success" href="#">Link 3</a>
            </div>
            <div class="col-md-3 text-center">
                <a class="text-success" href="#">Link 4</a>
            </div>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/bootstrap-sweetalert/dist/sweetalert.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    @RenderSection("Scripts", required: false)

    <script type="text/javascript">

        $(document).ready(function () {

            $("#searchStartDate").on("change", function (e) {
                $("#searchEndDate").attr("min", $(this).val());
            });

            if (typeof errors != "undefined") {

                $.each(errors, function (id, text) {

                    if (id == "errorMessage") {
                        swal({
                            text: text,
                            title: "Hata",
                            type: "error",
                            confirmButtonClass: "btn-danger",
                            confirmButtonText: "Tamam",
                            closeOnConfirm: false
                        });
                    } else if (id == "warningMessage") {
                        swal({
                            text: text,
                            title: "Uyarı",
                            type: "warning",
                            confirmButtonText: "Tamam",
                            confirmButtonClass: "btn-danger",
                            closeOnConfirm: false
                        });
                    } else if (id == "successMessage") {
                        swal({
                            text: text,
                            title: "Başarılı",
                            type: "success",
                            confirmButtonClass: "btn-success",
                            confirmButtonText: "Tamam",
                            closeOnConfirm: false
                        });
                    } else if (id == "infoMessage") {
                        swal({
                            text: text,
                            title: "Bilgi",
                            type: "info",
                            confirmButtonClass: "btn-info",
                            confirmButtonText: "Tamam",
                            closeOnConfirm: false
                        });
                    } else {
                        var itemId = "#" + id;
                        $(itemId).next().html(text).addClass("error field-validation-invalid");
                    }
                    //alert(id + "->" + text);
                });

            };
        });
    </script>
</body>
</html>